name: SSH build
on: [push]
jobs:
  fake-build:
    runs-on: ubuntu-latest
    steps:
      - name: Fake build
        run: |
          mkdir dist
          date > dist/build.txt
      - name: Upload file
        run: |
          scp -i ${{ secrets.SSH_PRIVATE_KEY }}\
          dist ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:~/dist
