name: SSH build
on: [push]
jobs:
  fake-build:
    runs-on: ubuntu-latest
    steps:
      - name: Fake build
        run: |
          mkdir dist
          date > dist/build.txt
      - name: Upload build artifact
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            mkdir -p /tmp/build
            scp -r dist ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/tmp/build
